### ISSUE TITLE
Cannot find PineTime

### ISSUE THREAD

**Issue by doniks** [alexr4535/siglo#21]
I just built siglo from source and started, I can scan, tried about a dozen times

Terminal says: [INFO ] Rescan button clicked

Application says: [INFO] Scan failed

I'm on Ubuntu. The system settings show the PineTime all the time . I've installed wasp-os on the PineTime https://github.com/daniel-thompson/wasp-os

![Screenshot from 2021-04-17 09-37-43](https://user-images.githubusercontent.com/26801304/115105662-a17e0700-9f60-11eb-8188-20cfa57524b6.png)

**Comment by alexr4535** [comment]
I did not write my app to support wasp-os, I wrote it to support infinitime. let me add the PineTime advertisement name to the whitelist.

**Comment by alexr4535** [comment]
Please try building siglo with this commit included: https://github.com/alexr4535/siglo/commit/9c6b04d4cde189ccb459168298fa254af750e9c2

**Comment by doniks** [comment]
Ah, I see. Still getting used to the pinetime ecosystem. but, fwiw, with this patch it finds the pinetime immediately!

**Comment by pfeerick** [comment]
In order to switch back to Infinitime, you'll need to flash the `reloader-factory.zip` from the 0.3.0 wasp-os release (0.4.0s reloader-factory.zip is broken)... but that will also put you back to 0.9.0 of Infinitime, and you'll also be on the old bootloader, so have to update that again. I think someone is going to look into updating the reloader with a more recent infinitime app and bootloader.

**Comment by pfeerick** [comment]
@alexr4535 wasp-os advertises under two names... `PineTime` when wasp-os is running normally, and `PineDFU` while in bootloader mode. Normal `PineTime` does not support DFU, it is in Nordic UART mode. `PineDFU` does, but I had no luck getting any further than just having siglo detect the PineDFU mode advertising... it did not appear to start downloading. I'll try again tomorrow, but I would suggest we need more wasp-os users to comment on this before it can be considered supported. I know wasp-os DFU does *something* different to Infinitime because it is quite a bit slower.
