### ISSUE TITLE
Receive Heartrate raw data to build tensorflow model

### ISSUE THREAD

**Issue by limoncelli** [alexr4535/siglo#33]
Just a thought on how it might be possible to improve heart rate accuracy.

If a lot of the community members collect raw sensor data, best if accompanied with some validated second heart rate sensor  (eg infrared or red light measurement), we could train a tensorflow model to get better predictions. Siglo itself could display the heart rate, or send it to pinetime for display or tensorflow lite could run directly with the trained model on the pinetime.

Might be something on the future wishlisi,

Thanks for all the effort

**Comment by pfeerick** [comment]
lol... HR reading was the last thing on my 0.1 milestone for a cli script I'm working on for playing with some of the InfiniTime/pinetime bluetooth capabiliites... so I went ahead and added it... It's crude, and barely works... but it should help if HR monitoring is added... https://github.com/pfeerick/InfiniTimeToy/commit/d80528f2eaeb641c1b725d4661cb6ea15cdb991b

**Comment by limoncelli** [comment]
Great,

is this the measurement value part:

# octet 1 - 3.88.2.1 
# octet 2 - HR (uint8) 

# octet 3 - HR (uint16)
and Octet 2 being the BPM? Is Octet 3 then the raw signal (wasp-OS had a video showing raw data)

How will one need to call the script from command line, once the device is paired. In the end I'm thknking of something of this type of style for the output:

Timestamp w millisec         BPM  raw
2021-05-03 15:21:02.0004   75     81
2021-05-03 15:21:02.0005   75     80
2021-05-03 15:21:02.0006   75     63
2021-05-03 15:21:02.0006   75     67
2021-05-03 15:21:02.0007   75     75
2021-05-03 15:21:02.0008   73     77
2021-05-03 15:21:02.0009   73     73

Thanks for your work. Really great. Will need to refresh python skills now...

**Comment by pfeerick** [comment]
I might be able to throw something together that does simply that in a day or two, but for starters, but I don't think InifiTime reports back that frequently or reports raw data... so it would probably have to be wasp-os specific, and I'd need to find out how it gives the raw data back... perhaps Daniel was just running a script on the pinetime that spat the info out in realtime, rather than via GATT BLE stuff..

My script as is isn't suitable, as it connects, does it's thing, and then disconnects... you really want it to connect, stay connected, and poll the HR until you Ctrl+C and then disconnect (as the absolute _simplest_ way to implement it). 

3.88.2.1 is one of the [headings in this document ](https://www.bluetooth.org/DocMan/handlers/DownloadDoc.ashx?doc_id=429632). Basically the Heart Rate characteristic is documented at 3.88, and consists of 

```
octet   1 = a bunch of flags - see 3.88.2.1 for the five flags
octet   2 = uint8 HR or first half uint16 HR if bit 0 of flags is 1
octet   3 = second half of  uint16 HR if bit 0 of flags is 1
octet 4-5 = energy expended if bit 3 of flags set to 1
octet 6-? = RR intervals (something about time between two R-Wave detection?) if bit 4 of flags set to 1 
```

**Comment by limoncelli** [comment]
thanks for the update. I will reach out to Daniel to see what his approach was and what data was actually displayed. All the best, robin

05.05.2021 11:07:21 Peter ***@***.***>:

**Comment by limoncelli** [comment]
Link to the request to Daniel in his wasp-os repo https://github.com/daniel-thompson/wasp-os/issues/204

05.05.2021 11:07:21 Peter ***@***.***>:

**Comment by limoncelli** [comment]
Reading [this at stackoverflow](https://stackoverflow.com/questions/17422218/bluetooth-low-energy-how-to-parse-r-r-interval-value) it looks lie one is to receive BPM directly from the device. I still think that postprocessing via trained model will enhance the result. Daniel talks in his video also about some filtering

**Comment by pfeerick** [comment]
So that must be what the RR-Intervals bit is, which is not implemented in InfiniTime, hence bit 4 of the flags octet is not set to 1. 

But it looks like you'll have more luck with wasp-os anyway, since Daniel just happens to be working on the same thing... how about that for timing! :laughing: I thought you'd have more luck that way anyway since you could probably write a python script that extracts the heart rate over the console... but being able to have it saved to device for later extraction is perfect... you can then run the HR app when you want to track the HR, for different training profiles, etc.

**Comment by limoncelli** [comment]
Somethings seem to land in infinitime 

https://github.com/JF002/InfiniTime/commit/e3ead332b9db3ad7b6acde933b6a7943b3ac81e2

they are referencing Daniels code which contains the way he calculates the heartrate 

https://github.com/daniel-thompson/wasp-os/blob/master/wasp/ppg.py

**Comment by pfeerick** [comment]
That's regarding an old PR, and just changes the variable(s) used so it
does use as much runtime memory.

When JF converted the code over, he erred in the side of caution when
setting the types, and made them signed rather than unsigned.

**Comment by pfeerick** [comment]
Sorry, int8 rather than int, not signed Vs unsigned.

**Comment by alexr4535** [comment]
I would rather have something like MyGNUHealth do heartrate and step counting than have siglo handle it.
